import { useEffect, useMemo, useState } from 'react'; import { useForm } from 'react-hook-form'; import { zodResolver } from '@hookform/resolvers/zod'; import { z } from 'zod';
import { TitleBar } from './components/layout/TitleBar'; import { Sidebar } from './components/layout/Sidebar'; import { StatusBar } from './components/layout/StatusBar'; import { HeroBanner } from './components/token/HeroBanner'; import { TokenConfiguration } from './components/token/TokenConfiguration'; import { LivePreview } from './components/token/LivePreview'; import { LaunchSteps } from './components/token/LaunchSteps'; import { ConsolePanel } from './components/token/ConsolePanel'; import { Modal } from './components/ui/Modal'; import { CostDialog } from './components/dialogs/CostDialog'; import { ConfirmationDialog } from './components/dialogs/ConfirmationDialog'; import { DeployDialog } from './components/dialogs/DeployDialog'; import { defaultConfig, type TokenConfig } from './types/token'; import { getNetwork, stamp } from './lib/utils';
const schema=z.object({name:z.string().trim().min(2,'Use at least 2 characters').max(50,'Maximum 50 characters'),symbol:z.string().trim().min(2,'Use at least 2 characters').max(10,'Maximum 10 characters').regex(/^[A-Z0-9]+$/,'Use uppercase letters and numbers'),supply:z.string().regex(/^[1-9]\d*$/,'Enter a positive whole number'),decimals:z.number().int().min(0,'Minimum is 0').max(18,'Maximum is 18'),network:z.enum(['bsc','ethereum','polygon','base','arbitrum','solana']),description:z.string().max(200,'Maximum 200 characters'),logo:z.string().optional(),mintable:z.boolean(),burnable:z.boolean(),pausable:z.boolean()});
type Dialog='cost'|'confirm'|'deploy'|'clear'|null;
export default function App(){const [drawer,setDrawer]=useState(false);const [wallet,setWallet]=useState('');const [connecting,setConnecting]=useState(false);const [dialog,setDialog]=useState<Dialog>(null);const [deployProgress,setDeployProgress]=useState(0);const [stage,setStage]=useState(0);const [messages,setMessages]=useState(()=>[`${stamp()}] Initializing token generator...`,`${stamp()}] Network: BSC (BEP20)`,`${stamp()}] Ready to configure Flask token.`]);const form=useForm<TokenConfig>({resolver:zodResolver(schema),defaultValues:defaultConfig,mode:'onBlur'});const config=form.watch();const network=getNetwork(config.network);const log=(m:string)=>setMessages(v=>[...v,`${stamp()}] ${m}`]);const apply=(v:Partial<TokenConfig>)=>Object.entries(v).forEach(([k,value])=>form.setValue(k as keyof TokenConfig,value as never,{shouldValidate:true}));
useEffect(()=>{const draft=localStorage.getItem('cryptoflask-draft');if(!draft)return;try{form.reset(schema.parse(JSON.parse(draft)));log('Saved draft restored from this device')}catch{localStorage.removeItem('cryptoflask-draft');log('Invalid saved draft was discarded')}},[]);
useEffect(()=>{if(dialog!=='deploy'||deployProgress>=4)return;const timer=setTimeout(()=>setDeployProgress(v=>v+1),650);return()=>clearTimeout(timer)},[dialog,deployProgress]);
useEffect(()=>{if(deployProgress===4){setStage(3);log('Simulation completed. No blockchain transaction was created.')}},[deployProgress]);
const networkLabel=useMemo(()=>config.network==='bsc'?'BSC Mainnet':network.label,[config.network,network.label]);
const connect=()=>{if(wallet)return;setConnecting(true);log('Wallet connection requested');setTimeout(()=>{setConnecting(false);const provider=(window as Window & {ethereum?:{request:(x:{method:string})=>Promise<string[]>}}).ethereum;if(provider){provider.request({method:'eth_requestAccounts'}).then(a=>{if(a[0]){setWallet(a[0]);log('Wallet connected with user approval')}}).catch(()=>log('Wallet connection cancelled'))}else log('No injected wallet provider found; continuing in simulation mode')},500)};
const generate=form.handleSubmit(()=>{setStage(1);setDialog('confirm');log('Generation review opened in simulation mode')});
return <div className="app-window"><TitleBar wallet={wallet} connecting={connecting} onConnect={connect} onDisconnect={()=>{setWallet('');log('Wallet disconnected')}} onMenu={()=>setDrawer(true)}/><div className="app-body"><Sidebar open={drawer} onClose={()=>setDrawer(false)}/><main><HeroBanner/><div className="workspace"><TokenConfiguration control={form.control} register={form.register} setValue={form.setValue} watch={form.watch} errors={form.formState.errors} onEvent={log} apply={apply} onClear={()=>setDialog('clear')}/><LivePreview config={config} onNetwork={v=>{form.setValue('network',v);log(`Network changed to ${getNetwork(v).label}`)}} onGenerate={generate} onSave={()=>{localStorage.setItem('cryptoflask-draft',JSON.stringify(config));log('Draft saved locally')}} onEstimate={()=>{setDialog('cost');log('Simulated cost estimate opened')}} preparing={false}/></div><LaunchSteps stage={stage}/><ConsolePanel messages={messages} onClear={()=>setMessages([])}/></main></div><StatusBar connected={!!wallet} network={networkLabel}/>{dialog==='cost'&&<CostDialog config={config} onClose={()=>setDialog(null)}/>} {dialog==='confirm'&&<ConfirmationDialog config={config} wallet={wallet} onClose={()=>{setDialog(null);log('Simulation cancelled')}} onConfirm={()=>{setDeployProgress(0);setStage(2);setDialog('deploy');log('Token simulation started')}}/>} {dialog==='deploy'&&<DeployDialog config={config} progress={deployProgress} onClose={()=>setDialog(null)} onAgain={()=>{form.reset(defaultConfig);setStage(0);setDialog(null);log('New token configuration started')}}/>} {dialog==='clear'&&<Modal title="Clear Token Configuration?" onClose={()=>setDialog(null)}><p className="modal-copy">This resets every token field and removes the uploaded logo. This action does not affect saved drafts.</p><div className="dialog-actions"><button onClick={()=>setDialog(null)}>Cancel</button><button className="danger" onClick={()=>{form.reset({...defaultConfig,name:'',symbol:'',supply:'',description:'',logo:undefined});setDialog(null);log('Token configuration cleared')}}>Clear All</button></div></Modal>}</div>}
